package javacore.exception.runtime.test;

public class RunTimeExceptionTest01 {
    public static void main(String[] args) {
        int numeros[] ={1,2};

        System.out.println(numeros[2]);
    }
}
